use crate::core::CountMatrix;
use crate::design::DesignMatrix;
use crate::dispersion::gene_est::{
    fit_dispersion_grid_with_prior, fit_dispersion_grid_with_prior_and_weights,
    fit_dispersion_line_search_no_cr_with_prior,
    fit_dispersion_line_search_no_cr_with_prior_and_weights, fit_dispersion_line_search_with_prior,
    fit_dispersion_line_search_with_prior_and_weights, DispersionPrior,
    GeneWiseDispersionFitMethod, GeneWiseDispersionOptions, WeightedDispersionFitInput,
};
use crate::errors::{invalid_dimensions, DeseqError};
use crate::matrix::RowMajorMatrix;

/// Options for DESeq2-style MAP dispersion fitting.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct MapDispersionOptions {
    /// Minimum final MAP dispersion estimate.
    pub min_disp: f64,
    /// Optional maximum final MAP dispersion estimate. Defaults to `max(10, n_samples)`.
    pub max_disp: Option<f64>,
    /// Outlier threshold multiplier on the log-dispersion residual scale.
    pub outlier_sd: f64,
    /// Apply Cox-Reid correction during the line-search MAP fit.
    pub use_cox_reid: bool,
    /// Threshold used by DESeq2 to choose samples for weighted Cox-Reid terms.
    pub weight_threshold: f64,
    /// DESeq2 Armijo line-search initial step size.
    pub kappa_0: f64,
    /// DESeq2 dispersion log-posterior convergence tolerance.
    pub disp_tol: f64,
    /// Maximum line-search iterations.
    pub maxit: usize,
    /// Number of points in each fallback log-alpha grid pass.
    pub grid_points: usize,
}

impl Default for MapDispersionOptions {
    fn default() -> Self {
        Self {
            min_disp: 1e-8,
            max_disp: None,
            outlier_sd: 2.0,
            use_cox_reid: true,
            weight_threshold: 1e-2,
            kappa_0: 1.0,
            disp_tol: 1e-6,
            maxit: 100,
            grid_points: 20,
        }
    }
}

impl From<GeneWiseDispersionOptions> for MapDispersionOptions {
    fn from(options: GeneWiseDispersionOptions) -> Self {
        Self {
            min_disp: options.min_disp,
            max_disp: options.max_disp,
            outlier_sd: 2.0,
            use_cox_reid: options.use_cox_reid,
            weight_threshold: options.weight_threshold,
            kappa_0: options.kappa_0,
            disp_tol: options.disp_tol,
            maxit: options.maxit,
            grid_points: options.grid_points,
        }
    }
}

/// Borrowed inputs for MAP dispersion fitting.
#[derive(Clone, Copy, Debug)]
pub struct MapDispersionInput<'a> {
    /// Raw count matrix.
    pub counts: &'a CountMatrix,
    /// Design matrix generated by R or caller code.
    pub design: &'a DesignMatrix,
    /// Fitted means from the gene-wise dispersion stage.
    pub mu: &'a RowMajorMatrix<f64>,
    /// Gene-wise dispersion estimates.
    pub disp_gene_est: &'a [f64],
    /// Fitted trend dispersions.
    pub disp_fit: &'a [f64],
    /// Per-gene all-zero flags.
    pub all_zero: &'a [bool],
    /// Optional row-normalized observation weights.
    pub observation_weights: Option<&'a RowMajorMatrix<f64>>,
    /// Variance of the normal prior on `log(alpha)`.
    pub disp_prior_var: f64,
    /// Robust variance of log-dispersion residuals used for outlier detection.
    pub var_log_disp_estimates: f64,
}

/// Output from DESeq2-style MAP dispersion fitting.
#[derive(Clone, Debug, PartialEq)]
pub struct MapDispersionOutput {
    /// Final dispersion estimates after outlier replacement.
    pub dispersion: Vec<f64>,
    /// Maximum a posteriori dispersion estimates before outlier replacement.
    pub disp_map: Vec<f64>,
    /// Line-search iteration counts.
    pub disp_iter: Vec<usize>,
    /// DESeq2-style dispersion outlier flags.
    pub disp_outlier: Vec<bool>,
    /// MAP convergence flags before grid fallback.
    pub converged: Vec<bool>,
    /// Initial dispersions used on entry to the MAP optimizer.
    pub disp_init: Vec<f64>,
    /// Prior variance used for fitting.
    pub disp_prior_var: f64,
}

/// Estimate MAP dispersions using DESeq2's no-weight `type="DESeq2"` shape.
///
/// For each non-all-zero gene, the initial value is `dispGeneEst` unless it is
/// at least one order of magnitude below the fitted trend, in which case
/// `dispFit` is used. The prior mean is `log(dispFit)`, and the prior variance
/// is the supplied `disp_prior_var`. Non-converged line-search rows fall back
/// to the prior-aware grid optimizer.
pub fn estimate_map_dispersions(
    input: MapDispersionInput<'_>,
    options: MapDispersionOptions,
) -> Result<MapDispersionOutput, DeseqError> {
    validate_map_inputs(&input, options)?;
    let max_disp = max_dispersion(options, input.counts.n_samples());
    let optimizer_options = optimizer_options(options);
    let mut dispersion = vec![f64::NAN; input.counts.n_genes()];
    let mut disp_map = vec![f64::NAN; input.counts.n_genes()];
    let mut disp_iter = vec![0; input.counts.n_genes()];
    let mut disp_outlier = vec![false; input.counts.n_genes()];
    let mut converged = vec![false; input.counts.n_genes()];
    let mut disp_init = vec![f64::NAN; input.counts.n_genes()];

    for gene in 0..input.counts.n_genes() {
        if input.all_zero[gene] {
            continue;
        }
        let gene_est = input.disp_gene_est[gene];
        let fit = input.disp_fit[gene];
        let initial = map_dispersion_initial_value(gene_est, fit)?;
        disp_init[gene] = initial;
        let prior = DispersionPrior::new(fit.ln(), input.disp_prior_var)?;
        let row_mu = input.mu.row(gene)?;
        let weight_row = input
            .observation_weights
            .map(|weights| weights.row(gene))
            .transpose()?;
        let line_search = if options.use_cox_reid {
            match weight_row {
                Some(weights) => {
                    fit_dispersion_line_search_with_prior_and_weights(WeightedDispersionFitInput {
                        counts: input.counts.row(gene)?,
                        mu: row_mu,
                        design: input.design,
                        initial_dispersion: initial,
                        options: optimizer_options,
                        n_samples: input.counts.n_samples(),
                        prior,
                        weights,
                    })?
                }
                None => fit_dispersion_line_search_with_prior(
                    input.counts.row(gene)?,
                    row_mu,
                    input.design,
                    initial,
                    optimizer_options,
                    input.counts.n_samples(),
                    prior,
                )?,
            }
        } else {
            match weight_row {
                Some(weights) => fit_dispersion_line_search_no_cr_with_prior_and_weights(
                    input.counts.row(gene)?,
                    row_mu,
                    initial,
                    optimizer_options,
                    input.counts.n_samples(),
                    prior,
                    weights,
                )?,
                None => fit_dispersion_line_search_no_cr_with_prior(
                    input.counts.row(gene)?,
                    row_mu,
                    initial,
                    optimizer_options,
                    input.counts.n_samples(),
                    prior,
                )?,
            }
        };
        let line_converged = line_search.iter < options.maxit;
        let mut map_value = line_search.dispersion;
        if !line_converged {
            map_value = match weight_row {
                Some(weights) => {
                    fit_dispersion_grid_with_prior_and_weights(WeightedDispersionFitInput {
                        counts: input.counts.row(gene)?,
                        mu: row_mu,
                        design: input.design,
                        initial_dispersion: map_value,
                        options: optimizer_options,
                        n_samples: input.counts.n_samples(),
                        prior,
                        weights,
                    })?
                    .0
                }
                None => {
                    fit_dispersion_grid_with_prior(
                        input.counts.row(gene)?,
                        row_mu,
                        input.design,
                        map_value,
                        optimizer_options,
                        input.counts.n_samples(),
                        prior,
                    )?
                    .0
                }
            };
        }
        map_value = map_value.clamp(options.min_disp, max_disp);
        let outlier = map_dispersion_outlier(
            gene_est,
            fit,
            options.outlier_sd,
            input.var_log_disp_estimates,
        );
        disp_map[gene] = map_value;
        disp_iter[gene] = line_search.iter;
        disp_outlier[gene] = outlier;
        converged[gene] = line_converged;
        dispersion[gene] = if outlier { gene_est } else { map_value };
    }

    Ok(MapDispersionOutput {
        dispersion,
        disp_map,
        disp_iter,
        disp_outlier,
        converged,
        disp_init,
        disp_prior_var: input.disp_prior_var,
    })
}

/// DESeq2's MAP dispersion initial value rule.
pub fn map_dispersion_initial_value(disp_gene_est: f64, disp_fit: f64) -> Result<f64, DeseqError> {
    validate_positive_fit_dispersion(disp_fit)?;
    if disp_gene_est.is_nan() {
        return Ok(disp_fit);
    }
    if !disp_gene_est.is_finite() || disp_gene_est <= 0.0 {
        return Err(DeseqError::InvalidDispersion {
            reason: "gene-wise dispersion must be finite and positive or NaN".to_string(),
        });
    }
    if disp_gene_est > 0.1 * disp_fit {
        Ok(disp_gene_est)
    } else {
        Ok(disp_fit)
    }
}

/// DESeq2's log-dispersion outlier rule for MAP dispersions.
pub fn map_dispersion_outlier(
    disp_gene_est: f64,
    disp_fit: f64,
    outlier_sd: f64,
    var_log_disp_estimates: f64,
) -> bool {
    if !disp_gene_est.is_finite()
        || disp_gene_est <= 0.0
        || !disp_fit.is_finite()
        || disp_fit <= 0.0
        || !outlier_sd.is_finite()
        || !var_log_disp_estimates.is_finite()
        || var_log_disp_estimates < 0.0
    {
        return false;
    }
    disp_gene_est.ln() > disp_fit.ln() + outlier_sd * var_log_disp_estimates.sqrt()
}

fn optimizer_options(options: MapDispersionOptions) -> GeneWiseDispersionOptions {
    GeneWiseDispersionOptions {
        min_disp: options.min_disp,
        max_disp: options.max_disp,
        min_mu: 0.5,
        grid_points: options.grid_points,
        use_cox_reid: options.use_cox_reid,
        weight_threshold: options.weight_threshold,
        fit_method: GeneWiseDispersionFitMethod::LineSearch,
        kappa_0: options.kappa_0,
        disp_tol: options.disp_tol,
        maxit: options.maxit,
        niter: 1,
    }
}

fn validate_map_inputs(
    input: &MapDispersionInput<'_>,
    options: MapDispersionOptions,
) -> Result<(), DeseqError> {
    if input.design.n_samples() != input.counts.n_samples() {
        return Err(invalid_dimensions(
            "MAP dispersion design samples",
            input.counts.n_samples(),
            input.design.n_samples(),
        ));
    }
    if input.mu.n_rows() != input.counts.n_genes() || input.mu.n_cols() != input.counts.n_samples()
    {
        return Err(DeseqError::InvalidDimensions {
            context: "MAP dispersion fitted means".to_string(),
            expected: input.counts.n_genes() * input.counts.n_samples(),
            actual: input.mu.len(),
        });
    }
    if input.disp_gene_est.len() != input.counts.n_genes() {
        return Err(invalid_dimensions(
            "MAP gene-wise dispersions",
            input.counts.n_genes(),
            input.disp_gene_est.len(),
        ));
    }
    if input.disp_fit.len() != input.counts.n_genes() {
        return Err(invalid_dimensions(
            "MAP fitted dispersions",
            input.counts.n_genes(),
            input.disp_fit.len(),
        ));
    }
    if input.all_zero.len() != input.counts.n_genes() {
        return Err(invalid_dimensions(
            "MAP all-zero flags",
            input.counts.n_genes(),
            input.all_zero.len(),
        ));
    }
    if let Some(weights) = input.observation_weights {
        if weights.n_rows() != input.counts.n_genes()
            || weights.n_cols() != input.counts.n_samples()
        {
            return Err(DeseqError::InvalidDimensions {
                context: "MAP observation weights".to_string(),
                expected: input.counts.n_genes() * input.counts.n_samples(),
                actual: weights.len(),
            });
        }
        for (idx, value) in weights.as_slice().iter().copied().enumerate() {
            if !value.is_finite() || value < 0.0 {
                return Err(DeseqError::NonFiniteValue {
                    context: "MAP observation weight".to_string(),
                    index: Some(idx),
                    value,
                });
            }
        }
    }
    validate_positive_scalar(input.disp_prior_var, "dispersion prior variance")?;
    if !input.var_log_disp_estimates.is_finite() || input.var_log_disp_estimates < 0.0 {
        return Err(DeseqError::InvalidDispersion {
            reason: "var_log_disp_estimates must be finite and non-negative".to_string(),
        });
    }
    validate_map_options(options, input.counts.n_samples())?;
    for gene in 0..input.counts.n_genes() {
        if input.all_zero[gene] {
            continue;
        }
        validate_positive_fit_dispersion(input.disp_fit[gene])?;
        if !input.disp_gene_est[gene].is_nan() {
            validate_positive_scalar(input.disp_gene_est[gene], "gene-wise dispersion")?;
        }
        for (sample, value) in input.mu.row(gene)?.iter().copied().enumerate() {
            if !value.is_finite() || value <= 0.0 {
                return Err(DeseqError::NonFiniteValue {
                    context: "MAP fitted mean".to_string(),
                    index: Some(gene * input.counts.n_samples() + sample),
                    value,
                });
            }
        }
    }
    Ok(())
}

fn validate_map_options(options: MapDispersionOptions, n_samples: usize) -> Result<(), DeseqError> {
    validate_positive_scalar(options.min_disp, "MAP min_disp")?;
    if (options.min_disp / 10.0).ln() <= -30.0 {
        return Err(DeseqError::InvalidDispersion {
            reason: "log(min_disp / 10) must be above -30 for numerical stability".to_string(),
        });
    }
    let max_disp = max_dispersion(options, n_samples);
    if !max_disp.is_finite() || max_disp <= options.min_disp {
        return Err(DeseqError::InvalidDispersion {
            reason: "max dispersion must be finite and greater than min dispersion".to_string(),
        });
    }
    validate_positive_scalar(options.outlier_sd, "MAP outlier_sd")?;
    if !options.weight_threshold.is_finite() || options.weight_threshold < 0.0 {
        return Err(DeseqError::InvalidDispersion {
            reason: "MAP weight_threshold must be finite and non-negative".to_string(),
        });
    }
    validate_positive_scalar(options.kappa_0, "MAP kappa_0")?;
    validate_positive_scalar(options.disp_tol, "MAP disp_tol")?;
    if options.maxit == 0 {
        return Err(DeseqError::InvalidDimensions {
            context: "MAP maxit".to_string(),
            expected: 1,
            actual: 0,
        });
    }
    if options.grid_points < 3 {
        return Err(DeseqError::InvalidDimensions {
            context: "MAP grid points".to_string(),
            expected: 3,
            actual: options.grid_points,
        });
    }
    Ok(())
}

fn validate_positive_fit_dispersion(value: f64) -> Result<(), DeseqError> {
    validate_positive_scalar(value, "fitted dispersion")
}

fn validate_positive_scalar(value: f64, name: &str) -> Result<(), DeseqError> {
    if !value.is_finite() || value <= 0.0 {
        return Err(DeseqError::InvalidDispersion {
            reason: format!("{name} must be finite and positive"),
        });
    }
    Ok(())
}

fn max_dispersion(options: MapDispersionOptions, n_samples: usize) -> f64 {
    options
        .max_disp
        .unwrap_or_else(|| 10.0_f64.max(n_samples as f64))
}
